# Generated by Django 5.2.7 on 2025-10-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
